/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tuacy_nestedscrolldemo_MainActivity */

#ifndef _Included_com_tuacy_nestedscrolldemo_MainActivity
#define _Included_com_tuacy_nestedscrolldemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tuacy_nestedscrolldemo_MainActivity
 * Method:    javaCallC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuacy_nestedscrolldemo_MainActivity_javaCallC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
